##### **Q1(a). Convert numbers =[1, 2.0, 3] to numpy array and convert all elements to string type.**

In [1]:
import numpy as np

In [4]:
my_Array = np.array([1,2.0,3], dtype='int64')
my_Array

array([1, 2, 3], dtype=int64)

In [8]:
string_Array = my_Array.astype(str)
string_Array

array(['1', '2', '3'], dtype='<U21')

In [9]:
my_Array = np.array([1,2.0,3], dtype='<U21')
my_Array

array(['1', '2.0', '3'], dtype='<U21')

##### **Q1(b). Create a 2 D array through list and set dtype as int32.**

In [21]:
my_List = [[2,3,4,5,6,7],[1,2,3,4,5,6],[5,6,7,8,9,0]]
np_array = np.array(my_List, dtype='int32')
np_array

array([[2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6],
       [5, 6, 7, 8, 9, 0]])

##### **Q1(c). Find the rows and columns of the 2d array created in part b.**

In [26]:
row, col = np_array.shape
print(f"Rows: {row}\nColumns: {col}")

Rows: 3
Columns: 6


##### **Q1(d). Print 10 random numbers between 1 and 100.**

In [42]:
np.random.randint(1, 101, 10)

array([93,  9,  1, 56, 51, 93, 28, 86, 90, 87])