***importing NumPy as np***

In [32]:
import numpy as np

***checking version***

In [33]:
np.__version__

'1.24.2'

***creating an array as numpy object***

In [34]:
np.array([3,5,6,8], dtype="int64")

array([3, 5, 6, 8], dtype=int64)

***creating an array of Zeros***

In [35]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [36]:
np.empty(4, dtype=int)

array([1634533486,  544433524,  543519329, 1635017327])

***creating an array of 1's***

In [37]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

***creating an array by defining a range***

In [38]:
a = np.arange(2, 13, 2, dtype=float)
a

array([ 2.,  4.,  6.,  8., 10., 12.])

***reshaping***

In [39]:
print("A\n", np.arange(4).reshape(2, 2), "\n")

A
 [[0 1]
 [2 3]] 



***array values at a regular interval***

In [40]:
a = np.linspace(10,20,5, dtype=complex)
a

array([10. +0.j, 12.5+0.j, 15. +0.j, 17.5+0.j, 20. +0.j])

In [41]:
rr = np.array([[2,3,4],[5,6,7]])
print(rr[0,2])

4


In [42]:
rrr = np.array([[[2,3,4],[5,6,7]], [[8,9,2], [3,4,5]]])
rrr[0,0,1]

3