In [89]:
import numpy as n

In [90]:
array= n.arange(10,51)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [91]:
array = n.ones(5, dtype='int32')*5
array

array([5, 5, 5, 5, 5])

In [92]:
matrix = n.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
iden = n.ones(9).reshape(3,3)
iden

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [94]:
n.eye(3,3, dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [95]:
rand = n.random.randn(25)
rand

array([ 0.52694315,  1.11446022, -0.43949969,  0.07894826,  1.72919645,
       -0.86206352, -0.50596041,  0.45795377,  0.62074161,  0.3136666 ,
       -0.36298893,  1.83480898, -0.50562918,  1.06609563, -2.14465237,
        0.46550935,  0.30388466,  0.31552553, -0.37055946, -0.77210416,
       -0.34906771, -0.21242677,  1.11293626, -0.85587714, -0.00573745])

In [96]:
rand.shape

(25,)

In [97]:
lin = n.linspace(0,1,20)

In [98]:
lin

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [99]:
import pandas as p

In [100]:
data = p.read_csv("Salaries.csv", low_memory=False)

In [101]:
data.shape

(148654, 13)

In [ ]:
data.describe

In [102]:
data.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [112]:
data[data["EmployeeName"] == "Glenn Frey"]["TotalPayBenefits"]

36587     248753.70
111330    241506.46
Name: TotalPayBenefits, dtype: float64